import type { Metadata } from 'next';
import './globals.css';
import { Theme } from '@radix-ui/themes';

export const metadata: Metadata = {
  title: '요즈미나의 므아지경',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
